### PR TITLE
Add sixel encoder option

### PR DESCRIPTION
**Pull request by AbeEstrada**
This implements the [sixel](https://github.com/saitoha/libsixel) encoder option (#12), only supported on iTerm2 and WezTerm (I also tested Kitty and Alacritty) at the moment and it is not compatible with any pager like `less`, `more`, `most`.

I really wanted better images, but it is very limited. I added the option as an exercise, feel free to close this PR if it doesn't get enough attention.

### CODE REVIEW

**Comment by AbeEstrada** [comment]
Alacritty: Add support for libsixel [#910](https://github.com/alacritty/alacritty/issues/910)

**Review by mrusme — APPROVED** [review]
Code looks good! TODO for the future: Since we're pulling in `http.Get` with this change, it would make sense to consolidate the image retrieval for ANSI and Sixel to a single place and make `ansimage` use the retrieved image, instead of using `NewScaledFromURL`.

**Comment by mrusme** [comment]
Thank you @AbeEstrada! Would you mind adding a usage info plus maybe a small screenshot of how the `-s` option's output looks like to the `README.md`?

**Comment by AbeEstrada** [comment]
@mrusme updated the README and added the screenshot.

I'm going to leave this https://www.arewesixelyet.com here for reference.

**Review by mrusme — APPROVED** [review]

**Comment by mrusme** [comment]
Thank you very much @AbeEstrada!

**Pull request merged**
